import defaultProfile from "../../../assets/karomi.jpg";

export const mockStudentData = [
  {
    sid: "1",
    id: "2021-100231",
    name: "Maria Dela Cruz",
    program: "BS in Computer Science",
    image: defaultProfile,
    studentProfile: {
      name: "Maria Anna Dela Cruz",
      nickname: "Ria",
      academicLevel: "College",
      newProgram: "BS in Computer Science",
      newLevel: "4th Year",
      newSection: "4.1",
      section: "CS 4.1",
      gender: "Female",
      birthday: "2002-05-15",
      nationality: "Filipino",
      religion: "Roman Catholic",
      status: "Single",
    },
    contactInfo: {
      email: "maria.delacruz@example.com",
      contactNo: "0917-123-4567",
      homeNo: "(046) 481-1400",
      address: {
        currentAddress: "123 Sampaguita St, Dasmariñas, Cavite",
        permanentAddress: "123 Sampaguita St, Dasmariñas, Cavite",
        provincialAddress: "N/A",
      },
    },
    familyBackground: {
      fatherInfo: { name: "Mario Dela Cruz", age: 50, /* ...other fields */ },
      motherInfo: { name: "Ana Dela Cruz", age: 48, /* ...other fields */ },
      emergency: {
        name: "Mario Dela Cruz",
        contactNo: "0918-987-6543",
      },
      guardian: { name: "Mario Dela Cruz", /* ...other fields */ },
      siblings: [],
    },
    educationalBackground: { 
      elementary: { schoolName: "Dasmariñas Elementary School" },
      juniorHighSchool: { schoolName: "Dasmariñas National High School" },
      seniorHighSchool: { schoolName: "De La Salle University - Dasmariñas" },
      college: { schoolName: "N/A" },
      /* ...other fields */
    },
    workExperience: { name: "N/A", /* ...other fields */ },
    interests: { sports: "Volleyball", hobbies: "Reading", talents: "Singing" },
    health: { illness: "None", /* ...other fields */ },
    lifeCircumstances: { recentLoss: "None", currentConcern: "Academic workload" },
  },
  {
    sid: "2",
    id: "2022-100456",
    name: "Juanito Gomez",
    program: "BS in Information Technology",
    image: defaultProfile,
    studentProfile: {
      name: "Juanito 'Jay' Gomez",
      nickname: "Jay",
      academicLevel: "College",
      newProgram: "BS in Information Technology",
      newLevel: "3rd Year",
      newSection: "3.2",
      section: "IT 3.2",
      gender: "Male",
      birthday: "2003-08-22",
      nationality: "Filipino",
      religion: "Christian",
      status: "Single",
    },
    contactInfo: {
      email: "juanito.gomez@example.com",
      contactNo: "0928-111-2222",
      homeNo: "(02) 8-845-1212",
      address: {
        currentAddress: "456 Rizal Ave, Silang, Cavite",
        permanentAddress: "456 Rizal Ave, Silang, Cavite",
        provincialAddress: "N/A",
      },
    },
    familyBackground: {
      fatherInfo: { name: "Jose Gomez", age: 52, /* ...other fields */ },
      motherInfo: { name: "Maria Gomez", age: 50, /* ...other fields */ },
      emergency: {
        name: "Maria Gomez",
        contactNo: "0919-333-4444",
      },
      guardian: { name: "Maria Gomez", /* ...other fields */ },
      siblings: [],
    },
    educationalBackground: { /* ...fill as needed... */ },
    workExperience: { /* ...fill as needed... */ },
    interests: { sports: "Basketball", hobbies: "Gaming", talents: "Guitar" },
    health: { illness: "Asthma", /* ...other fields */ },
    lifeCircumstances: { /* ...fill as needed... */ },
  },
];